version: 2
updates:
  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      # Ignore updates to packages that start with '@nx'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: '@nx*'
      - dependency-name: 'nx'
      # Ignore all updates
      - dependency-name: 'chalk'
      - dependency-name: 'prettier-plugin-java'
