name: Check nx-boot-gradle
on:
  workflow_dispatch:
jobs:
  Run_checks:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['18']
        java: ['17']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test nx-boot-gradle

      - name: Build
        run: npm run build nx-boot-gradle

      - name: E2E tests
        run: npm run nx run-many -- --target=e2e --projects=nx-boot-gradle-e2e,nx-boot-gradle-kt-e2e 
        env:
          NX_VERBOSE_LOGGING: 'true'
          GITHUB_ACTIONS: 'true'
