name: CI test
on:
  push:
jobs:
  gradle_macOS_latest:
    runs-on: macOS-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run test nx-boot-gradle

      - name: Build
        run: npm run build nx-boot-gradle

      - name: E2E tests
        run: npm run e2e nx-boot-gradle-e2e


  maven_macOS_latest:
    runs-on: macOS-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run test nx-boot-maven

      - name: Build
        run: npm run build nx-boot-maven

      - name: E2E tests
        run: npm run e2e nx-boot-maven-e2e
