name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  Run_checks:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: ['14', '16']
        java: ['11', '17']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run nx affected -- --target=test --parallel=3 --ci --code-coverage

      - name: Build
#        run: npm run nx affected -- --target=build --parallel=3
        run: npm run nx run-many -- --target=build --all --parallel=3

      - name: E2E tests
        run: npm run nx affected -- --target=e2e --parallel=3
        env:
          NX_VERBOSE_LOGGING: 'true'
          NX_E2E_SKIP_BUILD_CLEANUP: 'true'
