name: CI
on:
  workflow_dispatch:
  #  push:
  #    branches:
  #      - main
  #    paths-ignore:
  #      - '**.md'
  pull_request:
    branches:
      - main
    types: [assigned]
    paths-ignore:
      - '**.md'
jobs:
  Run_checks:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['18']
        java: ['17']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run nx run-many -- --target=lint

      - name: Unit tests
        run: npm run nx run-many -- --target=test

      - name: Build
        run: npm run nx run-many -- --target=build

      - name: E2E tests
        run: npm run nx run-many -- --target=e2e
        env:
          NX_VERBOSE_LOGGING: 'true'
          GITHUB_ACTIONS: 'true'
