name: E2e tests

on:
  # Trigger manually or on schedule
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  e2e:
    name: E2e tests
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node_version: ['18', '20']
        java: ['17']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run nx run-many -- --target=lint

      - name: Unit tests
        run: npm run nx run-many -- --target=test

      - name: Build
        run: npm run nx run-many -- --target=build

      - name: E2E tests
        run: npm run nx run-many -- --target=e2e
        env:
          NX_VERBOSE_LOGGING: 'true'
          GITHUB_ACTIONS: 'true'
