name: E2e Tests

on:
  # Trigger manually or on schedule
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  Run_checks:
    name: E2e Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: ['16', '18']
        java: ['17']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run nx run-many --all -- --target=build

      - name: E2E tests
        run: npm run nx run-many --all -- --target=e2e
        env:
          NX_VERBOSE_LOGGING: 'true'
          NX_E2E_SKIP_BUILD_CLEANUP: 'true'
          NX_CACHE_DIRECTORY: ${{ matrix.os }}-${{ matrix.node_version }}-${{ matrix.java }}
          GITHUB_ACTIONS: 'true'
