name: Run plugin e2e tests
on:
  workflow_dispatch:
    inputs:
      t_option:
        type: choice
        description: t option
        options:
          - nx-gradle
          - nx-gradle create-nx-gradle-workspace
          - nx-gradle gradle-root-directory e2e
          - nx-gradle gradle-root-directory kotlin dsl e2e
          - nx-gradle kmp kotlin dsl e2e
          - nx-gradle micronaut e2e
          - nx-gradle micronaut kotlin dsl e2e
          - nx-gradle all e2e
          - nx-gradle all kotlin dsl e2e
          - nx-gradle quarkus e2e
          - nx-gradle quarkus kotlin dsl e2e
          - nx-gradle spring-boot e2e
          - nx-gradle spring-boot kotlin dsl e2e
          - nx-maven
          - nx-maven all bom e2e
          - nx-maven create-nx-maven-workspace
          - nx-maven maven-root-directory e2e
          - nx-maven micronaut bom e2e
          - nx-maven micronaut-parent-pom e2e
          - nx-maven quarkus bom e2e
          - nx-maven spring-boot bom e2e
          - nx-maven spring-boot-parent-pom e2e
          - aggregatorProject - should generate java apps that use a parent project and aggregatorProject
      os:
        type: choice
        description: Os
        options:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

jobs:
  check_plugin:
    name: Running ${{ github.event.inputs.t_option }} tests from ${{ github.head_ref || github.ref_name }} branch on ${{ github.event.inputs.os }}
    strategy:
      matrix:
        node_version: ['20']
        java: ['17']
      fail-fast: true
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run nx run-many -- --target=lint

      - name: Unit tests
        run: npm run nx run-many -- --target=test

      - name: E2E tests
        run: npm run e2e jnxplus-e2e -- --t="${{ github.event.inputs.t_option }}"
        env:
          NX_VERBOSE_LOGGING: 'true'
          GITHUB_ACTIONS: 'true'
