name: Publish Plugin
on:
  workflow_dispatch:
    inputs:
      plugin:
        type: choice
        description: Plugin
        options:
          - nx-maven
          - nx-boot-maven
          - nx-quarkus-maven
          - nx-micronaut-maven
          - nx-gradle
          - nx-boot-gradle
          - nx-quarkus-gradle
          - nx-micronaut-gradle

jobs:
  publish_plugin:
    name: Publishing plugin ${{ github.event.inputs.plugin }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['18']
        java: ['17']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Version
        shell: bash
        run: npx nx version ${{ github.event.inputs.plugin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
