name: Smoke next tests

on:
  # Trigger manually or on schedule
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  smoke-next:
    name: Smoke next tests
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest]
        node_version: ['20']
        java: ['17']
    runs-on: ${{matrix.os}}
    env:
      NX_RUN_GROUP: ${{ github.run_id }}-v${{matrix.java}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Install dependencies
        run: npm i

      - run: npm run nx run-many -- --target=smoke-next
        env:
          NX_MAVEN_CLI_OPTS: '--no-transfer-progress'
          NX_SKIP_MAVEN_WRAPPER: 'true'
