name: Smoke tests

on:
  # Trigger manually or on schedule
  workflow_dispatch:
    inputs:
      tag_option:
        type: choice
        description: tag option
        options:
          - latest
          - previous
          - next
          - 0.50.0
      nx_tag_option:
        type: choice
        description: nx tag option
        options:
          - latest
          - previous
          - next
          - 18.3.5
          - 17.0.6
          - 16.10.0
  schedule:
    - cron: '0 0 * * *'

jobs:
  smoke:
    name: Smoke tests with nx ${{ github.event.inputs.nx_tag_option }} version and jnxplus ${{ github.event.inputs.tag_option }} version
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: ['18', '20']
        java: ['17']
    runs-on: ${{matrix.os}}
    env:
      NX_RUN_GROUP: ${{ github.run_id }}-v${{matrix.java}}
      NPM_TAG: ${{ github.event.inputs.tag_option }}
      NX_NPM_TAG: ${{ github.event.inputs.nx_tag_option }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i

      - run: npm run nx run-many -- --target=smoke
        env:
          NX_MAVEN_CLI_OPTS: '--no-transfer-progress -Dmaven.plugin.validation=VERBOSE'
